In [4]:
import pandas as pd

In [5]:
news = pd.read_csv("../../Datensaetze/news_POS_POS_tags_nouns_adjectives_verb.csv")

In [8]:
news

,category,filename,title,content,number_of_tokens,number_of_types,stemmed_text,POS_tags,POS,nouns,adjectives,verb
0,business,001.txt,Ad sales boost Time Warner profit,Quarterly profits at US media giant TimeWarne...,415.0,244.0,quarterli profit at US media giant timewarn j...,"['_SP', 'NNP', 'NNS', 'IN', 'NNP', 'NNS', 'NN'...",high fourth own fourth underlying exceptional ...,74.0,22.0,1.0
1,business,002.txt,Dollar gains on Greenspan speech,The dollar has hit its highest level against ...,379.0,230.0,the dollar ha hit it highest level against th...,"['_SP', 'DT', 'NN', 'VBZ', 'VBN', 'PRP$', 'JJS...",late recent sanguine current current next shar...,66.0,30.0,9.0
2,business,003.txt,Yukos unit buyer faces loan claim,The owners of embattled Russian oil giant Yuk...,258.0,168.0,the owner of embattl russian oil giant yuko a...,"['_SP', 'DT', 'NNS', 'IN', 'VBN', 'JJ', 'NN', ...",Russian former similar foreign Legal such real...,48.0,12.0,3.0
3,business,004.txt,High fuel prices hit BA's profits,British Airways has blamed high fuel prices f...,400.0,256.0,british airway ha blame high fuel price for a...,"['_SP', 'NNP', 'NNP', 'VBZ', 'VBN', 'JJ', 'NN'...",high pre - tax chief respectable third full la...,77.0,31.0,2.0
4,business,005.txt,Pernod takeover talk lifts Domecq,Shares in UK drinks and food firm Allied Dome...,260.0,178.0,share in UK drink and food firm alli domecq h...,"['_SP', 'NNP', 'IN', 'NNP', 'NNS', 'CC', 'NN',...",French last major global top other Last LVMH b...,42.0,13.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2220,tech,397.txt,BT program to beat dialler scams,BT is introducing two initiatives to help bea...,414.0,259.0,BT is introduc two initi to help beat rogu di...,"['_SP', 'NNP', 'VBZ', 'VBG', 'CD', 'NNS', 'TO'...",rogue net net able free pre - approved rogue p...,68.0,34.0,15.0
2221,tech,398.txt,Spam e-mails tempt net shoppers,Computer users across the world continue to i...,352.0,220.0,comput user across the world continu to ignor...,"['_SP', 'NNP', 'NNS', 'IN', 'DT', 'NN', 'VBP',...",organised personal alert Many online true legi...,67.0,21.0,11.0
2222,tech,399.txt,Be careful how you code,A new European directive could put software w...,1045.0,548.0,A new european direct could put softwar write...,"['_SP', 'DT', 'JJ', 'JJ', 'NN', 'MD', 'VB', 'N...",new European legal former Dutch controversial ...,150.0,83.0,23.0
2223,tech,400.txt,US cyber security chief resigns,The man making sure US computer networks are ...,374.0,208.0,the man make sure US comput network are safe ...,"['_SP', 'DT', 'NN', 'VBG', 'JJ', 'NNP', 'NN', ...",sure safe secure malicious other enough first ...,58.0,22.0,6.0
2224,tech,401.txt,Losing yourself in online gaming,"Online role playing games are time-consuming,...",2964.0,1137.0,"onlin role play game are time-consum , but en...","['_SP', 'JJ', 'NN', 'NN', 'NNS', 'VBP', 'NN', ...",Online last costly humorous good worrying popu...,436.0,188.0,131.0

In [7]:
news_sample = news.copy()
news_sample = news_sample.sample(frac=.25, replace=False, random_state=42)
news_sample

,category,filename,title,content,number_of_tokens,number_of_types,stemmed_text,POS_tags,POS,nouns,adjectives,verb
414,business,415.txt,UK house prices dip in November,"UK house prices dipped slightly in November, ...",395.0,201.0,"UK hous price dip slightli in novemb , the of...","['_SP', 'NNP', 'NN', 'NNS', 'VBD', 'RB', 'IN',...",average Recent monthly annual strong likely an...,73.0,27.0,4.0
420,business,421.txt,LSE 'sets date for takeover deal',The London Stock Exchange (LSE) is planning t...,361.0,209.0,the london stock exchang ( lse ) is plan to a...,"['_SP', 'DT', 'NNP', 'NNP', 'NNP', '-LRB-', 'N...",further tight last possible German formal furt...,65.0,19.0,7.0
1644,sport,332.txt,Harinordoquy suffers France axe,Number eight Imanol Harinordoquy has been dro...,337.0,214.0,number eight imanol harinordoquy ha been drop...,"['_SP', 'NN', 'CD', 'NNP', 'NNP', 'VBZ', 'VBN'...",second last second last second poor last fast ...,33.0,15.0,7.0
416,business,417.txt,Barclays shares up on merger talk,Shares in UK banking group Barclays have rise...,262.0,184.0,share in UK bank group barclay have risen on ...,"['_SP', 'NNP', 'IN', 'NNP', 'NN', 'NN', 'NNPS'...",late North American pre - tax similar full pre...,47.0,18.0,2.0
1232,politics,337.txt,Campaign 'cold calls' questioned,Labour and the Conservatives are still teleph...,575.0,282.0,labour and the conserv are still telephon the...,"['_SP', 'NNP', 'CC', 'DT', 'NNS', 'VBP', 'RB',...",sure cold personal major general unsolicited e...,73.0,31.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...
561,entertainment,052.txt,Spike Lee backs student directors,Film-maker Spike Lee says black representatio...,201.0,145.0,film-mak spike lee say black represent is str...,"['_SP', 'NN', 'HYPH', 'NN', 'NNP', 'NNP', 'VBZ...",black true old corporate old African American ...,34.0,15.0,2.0
867,entertainment,358.txt,Film star Fox behind theatre bid,Leading actor Edward Fox is one of the men be...,464.0,272.0,lead actor edward fox is one of the men behin...,"['_SP', 'VBG', 'NN', 'NNP', 'NNP', 'VBZ', 'CD'...",undisclosed nearby professional surprised beau...,58.0,19.0,6.0
1220,politics,325.txt,UKIP could sue Veritas defectors,The UK Independence Party could take legal ac...,315.0,185.0,the UK independ parti could take legal action...,"['_SP', 'DT', 'NNP', 'NNP', 'NNP', 'MD', 'VB',...",legal clear legal clear legal own fair square ...,39.0,18.0,3.0
1249,politics,354.txt,Brown names 16 March for Budget,Chancellor Gordon Brown will deliver his Budg...,285.0,181.0,chancellor gordon brown will deliv hi budget ...,"['_SP', 'NNP', 'NNP', 'NNP', 'MD', 'VB', 'PRP$...",likely last annual economic Next ninth little ...,33.0,19.0,3.0
1573,sport,261.txt,McClaren eyes Uefa Cup top spot,Steve McClaren wants his Middlesbrough team t...,147.0,102.0,steve mcclaren want hi middlesbrough team to ...,"['_SP', 'NNP', 'NNP', 'VBZ', 'PRP$', 'NNP', 'N...",knockout third fantastic tough semi fantastic ...,17.0,10.0,3.0

In [9]:
news_sample.to_csv("../../Datensaetze/news_sample_25percent.csv")